name: Build and Publish

on:
  workflow_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      continue: "false"
    strategy:
      matrix:
        service:
          - name: "ajeeshneudesic/auction-svc"
            path: "src/AuctionService"
          - name: "ajeeshneudesic/search-svc"
            path: "src/SearchService"
          - name: "ajeeshneudesic/identity-svc"
            path: "src/IdentityService"
          - name: "ajeeshneudesic/gateway-svc"
            path: "src/GatewayService"
          - name: "ajeeshneudesic/bid-svc"
            path: "src/BiddingService"
          - name: "ajeeshneudesic/notify-svc"
            path: "src/NotificationService"
          - name: "ajeeshneudesic/web-app"
            path: "frontend/web-app"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check for changes in service path
        run: |
          if git diff --quiet HEAD^ HEAD -- ${{matrix.service.path}}; then
            echo "No changes in ${{matrix.service.path}}. Skipping build"
            echo "continue=false" >> $GITHUB_ENV
          else
            echo "Changes detected in ${{matrix.service.path}}. Proceeding with build"
            echo "continue=true" >> $GITHUB_ENV
          fi

      - name: Setup docker buildx
        if: env.continue == 'true'
        uses: docker/setup-buildx-action@v2

      - name: Login to docker.
        if: env.continue == 'true'
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_TOKEN}}

      - name: Build and push
        if: env.continue == 'true'
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ${{matrix.service.path}}/Dockerfile
          push: true
          tags: ${{matrix.service.name}}:latest
